# Generated by Django 6.0 on 2025-12-21 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door', models.CharField(choices=[('I', 'ENTRANCE'), ('O', 'EXIT')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('A', 'ADMIN'), ('C', 'CUSTOMER')], default='C', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('M', 'MASTER'), ('m', 'MEMBER')], default='m', max_length=1)),
                ('card_model', models.CharField(choices=[('K', 'KEY CHAIN'), ('S', 'STICKER'), ('W', 'WRIST BAND')], default='S', max_length=1)),
                ('card_status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'IN ACTIVE'), ('L', 'LOST')], default='A', max_length=1)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer__first_name', 'customer__last_name'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('V', 'VILLA'), ('A', 'APPARTMENT')], max_length=1)),
                ('block', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('house_no', models.CharField(max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['house_type', 'block', 'floor', 'house_no'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='core.door')),
            ],
        ),
        migrations.CreateModel(
            name='DoorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doorpermissions', to='core.card')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doorpermissions', to='core.door')),
            ],
            options={
                'unique_together': {('card', 'door')},
            },
        ),
    ]
