# Generated by Django 6.0 on 2025-12-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('M', 'MASTER'), ('m', 'MEMBER')], default='m', max_length=1)),
                ('card_model', models.CharField(choices=[('K', 'KEY_CHAIN'), ('S', 'STICKER'), ('W', 'WRIST_BAND')], default='S', max_length=1)),
                ('card_status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'IN_ACTIVE'), ('L', 'LOST')], default='A', max_length=1)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('remark', models.TextField()),
            ],
            options={
                'ordering': ['customer__first_name', 'customer__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door', models.CharField(choices=[('I', 'ENTRANCE'), ('O', 'EXIT')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('V', 'VILLA'), ('A', 'APPARTMENT')], max_length=1)),
                ('block', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('house_no', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['house_type', 'block', 'floor', 'house_no'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
