# Generated by Django 6.0 on 2025-12-20 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.customer'),
        ),
        migrations.AddField(
            model_name='doorpermission',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doorpermissions', to='core.card'),
        ),
        migrations.AddField(
            model_name='doorpermission',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doorpermissions', to='core.door'),
        ),
        migrations.AddField(
            model_name='house',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.customer'),
        ),
        migrations.AddField(
            model_name='reader',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='core.door'),
        ),
        migrations.AlterUniqueTogether(
            name='doorpermission',
            unique_together={('card', 'door')},
        ),
    ]
