# Generated by Django 6.0 on 2025-12-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doorpermission',
            index=models.Index(fields=['can_access'], name='core_doorpe_can_acc_a4800c_idx'),
        ),
    ]
