# Generated by Django 6.0 on 2025-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doorpermission_core_doorpe_can_acc_a4800c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doorpermission',
            name='can_access',
            field=models.BooleanField(default=False),
        ),
    ]
