# Generated by Django 6.0 on 2026-01-18 12:26

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reader_api_key_alter_doorpermission_can_access'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', core.managers.CustomerManager()),
            ],
        ),
    ]
