# Generated by Django 6.0 on 2025-12-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_model',
            field=models.CharField(choices=[('K', 'KEY CHAIN'), ('S', 'STICKER'), ('W', 'WRIST BAND')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('I', 'IN ACTIVE'), ('L', 'LOST')], default='A', max_length=1),
        ),
    ]
