# Generated by Django 6.0.1 on 2026-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
