# Generated by Django 6.0 on 2025-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_card_card_model_alter_card_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='remark',
            field=models.CharField(max_length=250),
        ),
    ]
