# Generated by Django 6.0.1 on 2026-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_card_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
