# Generated by Django 6.0 on 2026-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_content_type_remove_payment_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='return_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
