# Generated by Django 6.0 on 2026-01-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_article_options_alter_payment_return_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
