"""
Django settings for gate_system project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
#storefront
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lvp#*%6%2e^#x62lp%rr-1v_3%djbx55ljep#a@)cpa1r4pb3y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*'
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djoser',
    'django_filters',
    'rest_framework',
    'debug_toolbar',
    'core',
    'logs',
    'payment',
    
 
]

AUTH_USER_MODEL = 'core.Customer'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

#user
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

import socket
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
    # Add your Docker or other network IP if needed
]

ROOT_URLCONF = 'gate_system.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    #'DEFAULT_PERMISSION_CLASSES': [
    #    'rest_framework.permissions.IsAuthenticated'
    #],
    'COERCE_DECIMAL_TO_STRING': False,
    #'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    #'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    #'PAGE_SIZE': 10,
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gate_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'smart_gate',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'bina1t1kassa@!',
        'PORT': '3306',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DJOSER = {
    'TOKEN_MODEL': None,
    'SERIALIZERS': {
        'user_create': 'core.serializers.UserCreateSerializer',
        'current_user': 'core.serializers.UserSerializer',
    },
}


SIMPLE_JWT = {
'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
'AUTH_HEADER_TYPES': ('JWT',),
'USER_ID_FIELD': 'phone_number',
'USER_ID_CLAIM': 'user_id',
}


from decouple import config
from pathlib import Path



CHAPA_MODE = config("CHAPA_MODE", default="TEST").upper()


CHAPA_PUBLIC_KEY = config("CHAPA_PUBLIC_KEY_TEST")
CHAPA_SECRET_KEY = config("CHAPA_SECRET_KEY_TEST")

    
    

#user1
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MDgwMjc1LCJpYXQiOjE3NjQ5OTM4NzUsImp0aSI6ImI3NDg1Y2I5MDIzNDQ5NGZhMWQ1N2E2MTU1ODEwNjRkIiwidXNlcl9pZCI6IjMifQ.RfNQREt74vSfn1I-ntkBSBxlpNobeD96c35JgIZ9vx4


#admin
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MDgxNTMzLCJpYXQiOjE3NjQ5OTUxMzMsImp0aSI6ImVkNTI2Y2JmMzVjNjQyMDdhY2Q1ZjNmZWZkOTljMGE4IiwidXNlcl9pZCI6IjEifQ.S6nq1AcvGFjfPn7A89jGmGhmZraJco8wsEZRTobqeTU

#jhon
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1MDkwMjYyLCJpYXQiOjE3NjUwMDM4NjIsImp0aSI6IjcxZjRmNTZlZDI5ZDQ0NzU5NzFhODI3NWQ5M2U2YTNiIiwidXNlcl9pZCI6IjIifQ.R7s93LjA_fIVPRpDY4t9VI4oCD8LDIMUkO7xxyT5Ph4