# Generated by Django 6.0 on 2025-12-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_doorpermission_core_doorpe_can_acc_a4800c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('access_granted', models.BooleanField(default=False)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.card')),
                ('door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.door')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.reader')),
            ],
            options={
                'ordering': ['-access_time'],
                'indexes': [models.Index(fields=['access_time'], name='logs_access_access__8ddd44_idx'), models.Index(fields=['access_granted'], name='logs_access_access__f56af9_idx'), models.Index(fields=['door', 'access_time'], name='logs_access_door_id_f66772_idx'), models.Index(fields=['card', 'access_time'], name='logs_access_card_id_ffea24_idx')],
            },
        ),
    ]
