# Generated by Django 6.0 on 2025-12-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='logs_access_card_715000_idx',
            old_name='logs_access_card_id_ffea24_idx',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='card',
            field=models.CharField(max_length=20),
        ),
    ]
