# Generated by Django 6.0 on 2025-12-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_logs_access_card_id_ffea24_idx_logs_access_card_715000_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
