# Generated by Django 6.0 on 2025-12-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reader_api_key_alter_doorpermission_can_access'),
        ('logs', '0003_accesslog_customer_accesslog_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('card', models.CharField(max_length=20)),
                ('customer', models.CharField(blank=True, max_length=150, null=True)),
                ('event', models.CharField(blank=True, max_length=30, null=True)),
                ('access_granted', models.BooleanField(default=False)),
                ('door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='core.door')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='core.reader')),
            ],
        ),
    ]
